name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include: 
          - os: macos-latest
            arch: amd64
            SIGSCAN_TARGET: sigscan-darwin-amd64
          - os: ubuntu-latest
            arch: amd64
            SIGSCAN_TARGET: sigscan-linux-amd64
          - os: windows-latest
            arch: amd64
            SIGSCAN_TARGET: sigscan-windows-amd64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - uses: actions/checkout@v3
      - name: Go Build
        run: make sigscan && mv ./sigscan ./${{ matrix.SIGSCAN_TARGET }}
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: sigscan-*
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Documentation Build
        run: go run ./hack/generate-manual
      - uses: actions/upload-artifact@v3
        with:
          name: man-pages
          path: man/

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Rename Artifacts
        run: |
          mkdir man
          mv man-pages/* man/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          body_path: CHANGELOG.md
          files: |
            artifacts/sigscan-*
            man/*